PROCESS BEFORE OUTPUT.
 MODULE STATUS_0300.
 MODULE CLEAR_OKCODE.
CALL SUBSCREEN SUB
    INCLUDING sy-repid gv_subs.
PROCESS AFTER INPUT.
CALL SUBSCREEN SUB.
MODULE EXIT_COMMAND_0300 AT EXIT-COMMAND.
MODULE USER_COMMAND_0300. 
